name: SIMDA tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.gitignore'

env:
  GO111MODULE: "on"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install PCAP dev library
        run: sudo apt install -y libpcap-dev

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: task test
